// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07fFWdO3Lk38FEtG29FmJKgJupuvRdbc',
    appId: '1:1026761389983:web:a3769ad16cf4ac6081afaa',
    messagingSenderId: '1026761389983',
    projectId: 'gupshup-chat-app-27',
    authDomain: 'gupshup-chat-app-27.firebaseapp.com',
    storageBucket: 'gupshup-chat-app-27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKG6xSAEGn6O71sTSWdYaBEWonQtFNVhg',
    appId: '1:1026761389983:android:7407324591707b8481afaa',
    messagingSenderId: '1026761389983',
    projectId: 'gupshup-chat-app-27',
    storageBucket: 'gupshup-chat-app-27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0LKUrMk6Pc2wpXwnQ-XsaQZQtFFCCEJA',
    appId: '1:1026761389983:ios:215c6141e2801e1981afaa',
    messagingSenderId: '1026761389983',
    projectId: 'gupshup-chat-app-27',
    storageBucket: 'gupshup-chat-app-27.firebasestorage.app',
    iosBundleId: 'com.example.gupShup',
  );
}
